# Generated by Django 2.2.13 on 2020-07-10 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNumDetail',
            fields=[
                ('readnum_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='read_statistic.ReadNum')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            bases=('read_statistic.readnum',),
        ),
    ]
