# Generated by Django 2.2.13 on 2020-07-15 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0003_auto_20200710_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
