# Generated by Django 2.2.13 on 2020-07-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200715_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaf_comment', to='comment.Comment'),
        ),
    ]
